Description: Toolchain template which provides the infrastructure resources needed to represent infrastcuture as code.
  This template specifically creates a CI/CD pipeline to build a model using a SageMaker Pipeline. This infrastructure
  provides a sample starter code for model building and sets up the infrastructure for re building the model on demand
  or when the code for the pipeline changes.
Parameters:
  SageMakerProjectName:
    Type: String
    Description: Name of the project
    MinLength: 1
    MaxLength: 32
    AllowedPattern: ^[a-zA-Z](-*[a-zA-Z0-9])*

  SageMakerProjectId:
    Type: String
    Description: Service generated Id of the project.

  ModelBuildCodeRepositoryBranch:
    Type: String
    Default: 'main'
    MaxLength: 255
    Description: Branch name for the Model Building and Training Code Repository

  ModelBuildCodeRepositoryFullname:
    Type: String
    MaxLength: 1024
    Description: Full repository name of the Model Building and Training Code Repository, which would be username/reponame or organizationname/reponame

  CodeConnectionArn:
    Type: String
    Description: Codestar Connection Arn for the Model Building, Training and Model Deployment Code Repository

Metadata:
  SagemakerTemplateParameterRules:
    ModelBuildCodeRepositoryBranch:
      Optional: true
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: "ModelBuild CodeRepository Info"
        Parameters:
          - ModelBuildCodeRepositoryBranch
          - ModelBuildCodeRepositoryFullname
    ParameterLabels:
      ModelBuildCodeRepositoryBranch:
        default: "Branch"
      ModelBuildCodeRepositoryFullname:
        default: "Full Repository Name"
      CodeConnectionArn:
        default: "Code Connection ARN"

Resources:

  MlOpsArtifactsBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !Sub sagemaker-project-${SageMakerProjectId} # 58 chars max/ 64 allowed

  SageMakerModelPipelineBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      # Max length: 255 chars
      Name: !Sub sagemaker-${SageMakerProjectName}-${SageMakerProjectId}-modelbuild # max: 10+33+15+10=68
      Description: Builds the model building workflow code repository, creates the SageMaker Pipeline and executes it
      ServiceRole: !Join [ ':', [ 'arn', !Ref 'AWS::Partition', 'iam:', !Ref 'AWS::AccountId', 'role/service-role/AmazonSageMakerProjectsCodeBuildRole'] ]
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:5.0
        EnvironmentVariables:
         - Name: SAGEMAKER_PROJECT_NAME
           Value: !Ref SageMakerProjectName
         - Name: SAGEMAKER_PROJECT_ID
           Value: !Ref SageMakerProjectId
         - Name: ARTIFACT_BUCKET
           Value: !Ref MlOpsArtifactsBucket
         - Name: SAGEMAKER_PIPELINE_NAME
           Value: !Sub sagemaker-${SageMakerProjectName}
         - Name: SAGEMAKER_PIPELINE_ROLE_ARN
           Value: !Join [ ':', [ 'arn', !Ref 'AWS::Partition', 'iam:', !Ref 'AWS::AccountId', 'role/service-role/AmazonSageMakerProjectsExecutionRole'] ]
         - Name: AWS_REGION
           Value: !Ref AWS::Region
      Source:
        Type: CODEPIPELINE
        BuildSpec: codebuild-buildspec.yml
      TimeoutInMinutes: 480

  ModelBuildPipeline:
    Type: AWS::CodePipeline::Pipeline
    DependsOn: MlOpsArtifactsBucket
    Properties:
      # Max length: 100 chars
      Name: !Sub sagemaker-${SageMakerProjectName}-${SageMakerProjectId}-modelbuild # max: 10+33+15+10=68
      RoleArn: !Join [ ':', [ 'arn', !Ref 'AWS::Partition', 'iam:', !Ref 'AWS::AccountId', 'role/service-role/AmazonSageMakerProjectsCodePipelineRole'] ]
      PipelineType: V2
      ArtifactStore:
        Type: S3
        Location:
          !Ref MlOpsArtifactsBucket
      Stages:
        - Name: Source
          Actions:
            - Name: ModelBuildWorkflowCode
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeStarSourceConnection
                Version: 1
              Configuration:
                ConnectionArn: !Sub ${CodeConnectionArn}
                FullRepositoryId: !Sub ${ModelBuildCodeRepositoryFullname}
                BranchName: !Sub ${ModelBuildCodeRepositoryBranch}
              OutputArtifacts:
                - Name: ModelBuildSourceArtifact

        - Name: Build
          Actions:
            - Name: BuildAndExecuteSageMakerPipeline
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              InputArtifacts:
                - Name: ModelBuildSourceArtifact
              OutputArtifacts:
                - Name: ModelBuildBuildArtifact

              Configuration:
                ProjectName: !Ref SageMakerModelPipelineBuildProject
              RunOrder: 1

  GitSeedCodeCheckinProject:
    Type: AWS::CodeBuild::Project
    Properties:
      # Max length: 255 chars
      Name: !Sub sagemaker-${SageMakerProjectName}-${SageMakerProjectId}-git-seedcodecheckin # max: 10+33+15+19=77
      Description: Checkin the initial seedcode into the given repository
      ServiceRole: !Join [ ':', [ 'arn', !Ref 'AWS::Partition', 'iam:', !Ref 'AWS::AccountId', 'role/service-role/AmazonSageMakerProjectsCodeBuildRole'] ]
      Artifacts:
        Type: NO_ARTIFACTS
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: 'aws/codebuild/amazonlinux2-x86_64-standard:5.0'
      Source:
        Type: S3
        Location: !Join 
        - ''
        - - 'sagemaker-servicecatalog-seedcode-'
          - !Ref 'AWS::Region'
          - '/bootstrap/GitRepositorySeedCodeCheckinCodeBuildProject-v1.1.zip'
        BuildSpec: buildspec.yml
      TimeoutInMinutes: 14

  GitSeedCodeCheckinProjectTriggerLambda:
    DependsOn: GitSeedCodeCheckinProject
    Type: 'AWS::Lambda::Function'
    Properties:
      Description: To trigger the codebuild project for the seedcode checkin
      Handler: index.lambda_handler
      Runtime: python3.12
      FunctionName: !Sub sagemaker-${SageMakerProjectId}-git-seedcodecheckin # max: 10+15+19=44 out of 64 max
      Timeout: 900
      Role: !Join [ ':', [ 'arn', !Ref 'AWS::Partition', 'iam:', !Ref 'AWS::AccountId', 'role/service-role/AmazonSageMakerProjectsLambdaRole'] ]
      Code:
        ZipFile: |
          import boto3
          import cfnresponse
          import os
          import time
          from botocore.exceptions import ClientError

          # This function should be triggered by the custom resource in the cfn template, Called along with the
          # seedcode information (what code needs to be populated), the git repository information (where it
          # needs to be populated) and the git codestar connection information. This would inturn trigger
          # the codebuild which does the population of the seedcode
          def lambda_handler(event, context):
            responseData = {}
            if event['RequestType'] == 'Create':
              try:
                time.sleep(20) # Sleep for few seconds before triggering seed code for configuration update of code build.
                print("Starting seed code checkin")
                client = boto3.client('codebuild')
                response = retry_on_access_denied(lambda: client.start_build(
                  projectName=os.environ['CodeBuildProjectName'],
                  environmentVariablesOverride=get_build_environment_variables_override(event),
                  secondarySourcesOverride=get_secondary_sources_override(event)
                ))
                poll_timeout = 840 # This Value is assigned based on the codebuild project timeout value
                max_poll_time = time.time() + poll_timeout
                print("Polling Codebuild to check if seed check checkin is complete")
                build_status = poll_and_get_build_status(client, response['build']['id'], max_poll_time)
                if (build_status != 'SUCCEEDED'):
                  if (time.time() > max_poll_time and build_status == 'IN_PROGRESS'):
                    failure_reason = 'Codebuild to checkin seedcode did not complete within ' + poll_timeout + ' seconds'
                  else:
                    failure_reason = 'Codebuild to checkin seedcode has status ' + build_status
                  cfnresponse.send(event, context, cfnresponse.FAILED, responseData, reason=failure_reason)
                else:
                  responseData['url'] = get_repository_url(event)
                  cfnresponse.send(event, context, cfnresponse.SUCCESS, responseData)
              except Exception as err:
                print("An exception occurred", err)
                cfnresponse.send(event, context, cfnresponse.FAILED, responseData, reason=str(err))
            else:
              cfnresponse.send(event, context, cfnresponse.SUCCESS, responseData)

          def retry_on_access_denied(func, max_retries=3, initial_delay=1):
            retries = 0
            delay = initial_delay
          
            while retries < max_retries:
              try:
                return func()
              except ClientError as e:
                if e.response['Error']['Code'] == 'AccessDeniedException':
                  print(f"AccessDenied error occurred. Retrying in {delay} seconds...")
                  time.sleep(delay)
                  retries += 1
                  delay *= 2  # Exponential backoff
                else:
                  raise  # Re-raise the exception if it's not AccessDenied
          
            raise Exception(f"Max retries ({max_retries}) exceeded. Unable to perform the operation.")
          
          def get_build_environment_variables_override(event):
            return [
              {
                'name': 'GIT_REPOSITORY_BRANCH',
                'value': event['ResourceProperties']['GIT_REPOSITORY_BRANCH'],
                'type': 'PLAINTEXT'
              },
              {
                'name': 'GIT_REPOSITORY_URL',
                'value': get_repository_url(event),
                'type': 'PLAINTEXT'
              }
            ]
          
          def get_secondary_sources_override(event):
            return [
              {
                'location': '{}/{}'.format(event['ResourceProperties']['SEEDCODE_BUCKET_NAME'], event['ResourceProperties']['SEEDCODE_BUCKET_KEY']),
                'type': 'S3',
                'sourceIdentifier': 'source'
              }
            ]
          
          def get_repository_url(event):
            parsed_connection_arn = parse_arn(event['ResourceProperties']['GIT_REPOSITORY_CONNECTION_ARN'])
            url_prefix = 'codeconnections'
            if 'codestar-connections' in parsed_connection_arn['service']:
              url_prefix = 'codestar-connections'
            return 'https://{}.{}.amazonaws.com/git-http/{}/{}/{}/{}.git'.format(url_prefix, 
              parsed_connection_arn['region'], parsed_connection_arn['account'], parsed_connection_arn['region'], parsed_connection_arn['resource'], 
              event['ResourceProperties']['GIT_REPOSITORY_FULL_NAME'])
          
          def parse_arn(arn):
            # http://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html
            elements = arn.split(':', 5)
            result = {
              'arn': elements[0],
              'partition': elements[1],
              'service': elements[2],
              'region': elements[3],
              'account': elements[4],
              'resource': elements[5],
              'resource_type': None
            }
            if '/' in result['resource']:
              result['resource_type'], result['resource'] = result['resource'].split('/',1)
            elif ':' in result['resource']:
              result['resource_type'], result['resource'] = result['resource'].split(':',1)
            return result

          def poll_and_get_build_status(client, build_id, max_poll_time):
            # usually it takes around 70 to 85 seconds for initializing the codebuild and
            # for the seedcode to get checked in
            initial_poll_interval = 60
            poll_interval = 15
            time.sleep(initial_poll_interval)
            build_status='IN_PROGRESS'
            while build_status == 'IN_PROGRESS' and time.time() < max_poll_time:
                build_status = retry_on_access_denied(lambda: client.batch_get_builds(ids=[build_id]))['builds'][0]['buildStatus']
                time.sleep(poll_interval)
            return build_status

      Environment:
        Variables:
          CodeBuildProjectName: !Sub sagemaker-${SageMakerProjectName}-${SageMakerProjectId}-git-seedcodecheckin

  SageMakerModelBuildSeedCodeCheckinProjectTriggerLambdaInvoker:
    Type: 'AWS::CloudFormation::CustomResource'
    DependsOn: GitSeedCodeCheckinProjectTriggerLambda
    Properties:
      ServiceToken: !GetAtt
        - GitSeedCodeCheckinProjectTriggerLambda
        - Arn
      SEEDCODE_BUCKET_NAME: !Join 
      - ''
      - - 'sagemaker-servicecatalog-seedcode-'
        - !Ref 'AWS::Region'
      SEEDCODE_BUCKET_KEY: toolchain/model-building-workflow-v1.0.zip
      GIT_REPOSITORY_FULL_NAME: !Sub ${ModelBuildCodeRepositoryFullname}
      GIT_REPOSITORY_BRANCH: !Sub ${ModelBuildCodeRepositoryBranch}
      GIT_REPOSITORY_CONNECTION_ARN: !Sub ${CodeConnectionArn}

  ModelBuildSagemakerCodeRepository:
    Type: 'AWS::SageMaker::CodeRepository'
    Properties:
      CodeRepositoryName: !Sub sagemaker-${SageMakerProjectId}-modelbuild # max: 10+15+11=36 out of 63 max
      GitConfig:
        Branch: !Sub ${ModelBuildCodeRepositoryBranch}
        RepositoryUrl: !GetAtt
          - SageMakerModelBuildSeedCodeCheckinProjectTriggerLambdaInvoker
          - url